---
# == Work Dir for replicated log
- name: create work dir
  file: path=/var/mesos state=directory

# == Remove default configs
- name: Remove Default Mesos Configs
  file: state=directory path=/etc/mesos/

- name: Remove Mesos ZK File
  file: state=absent path=/etc/mesos/zk

- name: Remove Default Mesos-Master Config
  file: state=absent path=/etc/mesos-master/

- name: Remove Default Mesos-Slave Config
  file: state=absent path=/etc/mesos-slave/

# == Configure and recreate

- name: Mesos default config file
  template: src=conf-mesos.j2 dest=/etc/default/mesos

- name: Mesos Master config file
  template: src=conf-mesos-master.j2 dest=/etc/default/mesos-master
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: Mesos Slave config file
  template: src=conf-mesos-slave.j2 dest=/etc/default/mesos-slave
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"

- name: start mesos-master
  service: name=mesos-master state=started
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: disable mesos-master if only slave
  service: name=mesos-master state=stopped enabled=false
  when: mesos_install_mode == "slave"

- name: start mesos-slave
  service: name=mesos-slave state=started enabled=true
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
