---
- name: Add mesosphere repo
  yum: name=http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm state=present

- name: remove old repo
  yum: name=http://repos.mesosphere.io/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm state=absent

- name: Install os packages
  yum: name={{item}} state=present
  with_items:
    - wget
    - curl
    - unzip
    - libselinux-python
    - python-setuptools
    - cyrus-sasl-lib
    - cyrus-sasl
    - mesos-{{mesos_version}}

- name: mesos-master systemd unit
  template: src=mesos-master.service.j2 dest=/usr/lib/systemd/system/mesos-master.service
  when: mesos_install_mode == "master" or mesos_install_mode == "master-slave"

- name: mesos-slave systemd unit
  template: src=mesos-slave.service.j2 dest=/usr/lib/systemd/system/mesos-slave.service
  when: mesos_install_mode == "slave" or mesos_install_mode == "master-slave"
